### PR TITLE
Lab2

### PR DESCRIPTION
**Pull request by williamdolsen**

### CODE REVIEW

**Comment by williamdolsen** [comment]
problem 1 part c plot a Gaussian on the semi-log plot

**Comment by jenniv27** [comment]
In problem 1 part D it may be more clear to remind the reader that the value 4.1 is the average number of gamma-rays emitted by the hypothetical source

**Comment by williamdolsen** [comment]
problem 2b plot the gaussian on the plot and update analysis accordingly

**Comment by jenniv27** [comment]
In Problem 2 part A, I am not sure why the mean seems to shift so aggressively between the average of 1 Rayleigh and 2 Rayleigh distributions. The x-scale also looks very different between your base Rayleigh and the averages. I looked through the code and couldn't figure out the issue but it looks like some kind of scaling problem.

**Comment by jenniv27** [comment]
Other note about Problem 2A, the width starts very narrow then becomes suddenly wide, then starts getting narrow again. Once the graph scale gets fixed I'm sure this will be more consistent too

**Comment by jenniv27** [comment]
Great work!

**Pull request merged**
